### ISSUE TITLE
1주차 스터디 자료 업로드 - SparkSQL

### ISSUE THREAD

**Issue by syohnet** [modulabs/distributed_system#1]
- [빅데이터 분석을 위한 스파크 2 프로그래밍 - 대용량 데이터 처리부터 머신러닝까지](http://wikibook.co.kr/spark/) 스터디 1주차 자료 업로드
  - 05장: 스파크 SQL 요약자료
    - 5.1 데이터셋
    - 5.2 연산의 종류와 주요 API
    - 5.3 코드 작성 절차 및 단어 수 세기 예제
    - 5.4 스파크세션
- [x] 파일명 규약지켰는지
- [x] 실습파일 함께 업데이트 되었는지

**Comment by syohnet** [comment]
@lovablebaby 기존 올린 파일명 참고해서 파일명 작성하였습니다. 파일명 기준에 맞춰 확인해주세엽

**Comment by lovablebaby** [comment]
확인하였습니다. 고생하셨어요!
